version: '3.7'

services:
  frontend:
    build:
      context: ./angular-app
    ports:
      - "4200:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/db:/app/db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./db/versicherung.db

volumes:
  sqlite_db:
